version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aiou_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0"
    volumes:
      - ./backend:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/1
    tty: true
    stdin_open: true

  sidekiq:
    build: ./backend
    command: bundle exec sidekiq
    volumes:
      - ./backend:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/1

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - node_modules_cache:/app/node_modules
    ports:
      - "3001:3001"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
  node_modules_cache:
